### ISSUE TITLE
大佬可否做个连续对话？

### ISSUE THREAD

**Issue by VAHua** [Alpaca4610/nonebot-plugin-bard#2]
比如触发连续对话命令“bardchat”，机器人回复“对话开始”，发送“对话结束”机器人发送“结束对话”，结束连续对话
群聊的时候就需要区分每个人的连续对话，就需要用QQ号区分了

**Comment by Alpaca4610** [comment]
现在谷歌的bard升级为gemini，相关的库也在更新中，我测试时出现了一些bug，等gemini的逆向API库稳定之后可以考虑。

**Comment by Alpaca4610** [comment]
请查看最新的README，已更新https://github.com/Alpaca4610/nonebot-plugin-bard/commit/f8b778d3ebf3512c8c10215f8b979fe4339dfb77

**Comment by VAHua** [comment]
> 请查看最新的README，已更新[f8b778d](https://github.com/Alpaca4610/nonebot-plugin-bard/commit/f8b778d3ebf3512c8c10215f8b979fe4339dfb77)

收到，谢谢大佬！
