### ISSUE TITLE
pip无法升级，卡在了0.3.0

### ISSUE THREAD

**Issue by VAHua** [Alpaca4610/nonebot-plugin-bard#5]
![image](https://github.com/Alpaca4610/nonebot-plugin-bard/assets/129832780/824dcc97-fbda-4f63-95dc-1e227f02f5a6)

我卸载了重装，也只能安装0.3.0，使用--upgrade，也不能升级，不知为何

**Comment by Alpaca4610** [comment]
上次发版的时候pip出了问题没有上传成功，刚刚已经发布0.3.3到pypi了。

**Comment by VAHua** [comment]
> 上次发版的时候pip出了问题没有上传成功，刚刚已经发布0.3.3到pypi了。

收到，已更新
