### ISSUE TITLE
有些问题报错

### ISSUE THREAD

**Issue by VAHua** [Alpaca4610/nonebot-plugin-bard#6]
部分问题报错，原因不详，请大佬帮忙看一下下
![image](https://github.com/Alpaca4610/nonebot-plugin-bard/assets/129832780/76f3db9e-81ca-469f-beaa-ca2a03ee9257)

**Comment by Alpaca4610** [comment]
之前有这个报错吗

**Comment by VAHua** [comment]
> 之前有这个报错吗

有过，你可以也试试这个问题

**Comment by VAHua** [comment]
补两张图片
![image](https://github.com/Alpaca4610/nonebot-plugin-bard/assets/129832780/5421f6c5-5b04-4f00-9175-0a07a22babb0)
![image](https://github.com/Alpaca4610/nonebot-plugin-bard/assets/129832780/d709eafb-a522-4853-9dd9-82bc8d2376c9)
就这个普者黑不行

**Comment by Alpaca4610** [comment]
![image](https://github.com/Alpaca4610/nonebot-plugin-bard/assets/16055526/a2ac2e00-3a1d-455d-9a70-91f80630262e)
应该是Gemini返回了图片，但是机器人框架那边没有写处理图片的代码，所以报错了。我有时间看看咋解决。

**Comment by VAHua** [comment]
> ![image](https://private-user-images.githubusercontent.com/16055526/316376107-a2ac2e00-3a1d-455d-9a70-91f80630262e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMzY5MDMsIm5iZiI6MTcxMTMzNjYwMywicGF0aCI6Ii8xNjA1NTUyNi8zMTYzNzYxMDctYTJhYzJlMDAtM2ExZC00NTVkLTlhNzAtOTFmODA2MzAyNjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDAzMTY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzOGUyOGNjMDYxNDYwNzEwMWFjYjhhMGZjMmZlNDZkM2U5NmE1ZWIxZmY5Mjk4ZDE1MmE3ZGI1OWJlMzRkMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Obo4CGThj610eKGRJT-2ahsMDHl9ZC15DMEFpSygajQ) 应该是Gemini返回了图片，但是机器人框架那边没有写处理图片的代码，所以报错了。我有时间看看咋解决。

哦哦，原来是这样，那加个判断是不是有图片的url

**Comment by VAHua** [comment]
> ![image](https://private-user-images.githubusercontent.com/16055526/316376107-a2ac2e00-3a1d-455d-9a70-91f80630262e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MjY0NDgsIm5iZiI6MTcxMjYyNjE0OCwicGF0aCI6Ii8xNjA1NTUyNi8zMTYzNzYxMDctYTJhYzJlMDAtM2ExZC00NTVkLTlhNzAtOTFmODA2MzAyNjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDAxMjkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MmU1ZTI0MmY5ZmJlYThiMGRiZGFhZjk3OTcwMjU3ZGYwMzhhZmE0ZGNhNDg5Y2MxNjM1ZjVhMGRjOGY4ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KgGj3rUoOjh1E_sIz-sveOUJLQzpuewTIVpp3aDPt7Y) 应该是Gemini返回了图片，但是机器人框架那边没有写处理图片的代码，所以报错了。我有时间看看咋解决。

大佬大佬，求解决，嘤嘤嘤

**Comment by Alpaca4610** [comment]
刚刚看了一下，应该是gemini API包那边的问题，我现在把最新的API包直接当做依赖安装，bug虽然解决了，但可能会出现一些依赖问题。

**Comment by VAHua** [comment]
> 刚刚看了一下，应该是gemini API包那边的问题，我现在把最新的API包直接当做依赖安装，bug虽然解决了，但可能会出现一些依赖问题。

依赖的话我就缺啥补啥，管他三七二十一一直pip

**Comment by Alpaca4610** [comment]
> > 刚刚看了一下，应该是gemini API包那边的问题，我现在把最新的API包直接当做依赖安装，bug虽然解决了，但可能会出现一些依赖问题。
> 
> 依赖的话我就缺啥补啥，管他三七二十一一直pip

可能会出现依赖冲突问题

**Comment by Alpaca4610** [comment]
如果不着急的话可以先用着旧版，新版建议备份一份原始的环境然后再安装。

**Comment by VAHua** [comment]
> 如果不着急的话可以先用着旧版，新版建议备份一份原始的环境然后再安装。

好哒，谢谢大佬！

**Comment by VAHua** [comment]
> 如果不着急的话可以先用着旧版，新版建议备份一份原始的环境然后再安装。

大佬，你4.0的好像没提上去

**Comment by Alpaca4610** [comment]
> > 如果不着急的话可以先用着旧版，新版建议备份一份原始的环境然后再安装。
> 
> 大佬，你4.0的好像没提上去

👌等我有空发个包

**Comment by Alpaca4610** [comment]
> > 如果不着急的话可以先用着旧版，新版建议备份一份原始的环境然后再安装。
> 
> 大佬，你4.0的好像没提上去

之前已经提过了呀，我刚刚提了一次显示版本冲突了。

**Comment by Alpaca4610** [comment]
新的稳定版0.5.0已发布

**Comment by VAHua** [comment]
> 新的稳定版0.5.0已发布

谢谢大佬，爱你么么哒
