### ISSUE TITLE
似乎如果回答有图片，还是发不出来呢

### ISSUE THREAD

**Issue by VAHua** [Alpaca4610/nonebot-plugin-bard#9]
![image](https://github.com/Alpaca4610/nonebot-plugin-bard/assets/129832780/538993eb-d28b-475b-869f-88fcbe16400f)

**Comment by Alpaca4610** [comment]
orz,我传错包了，昨天修改之后的代码没有传上来，等会我更新一版。

**Comment by Alpaca4610** [comment]
0.5.1已更新

**Comment by VAHua** [comment]
回答报错Failed to initiate client. Request failed with status code 429，是什么原因呢，已更新了token也一样

**Comment by Alpaca4610** [comment]
> 回答报错Failed to initiate client. Request failed with status code 429，是什么原因呢，已更新了token也一样

429表示客户端发送的请求过多，服务器暂时无法处理。过一段时间之后看看？

**Comment by VAHua** [comment]
谢谢大佬，已解决
